server {
    server_name anmar.enterprises www.anmar.enterprises anmarenterprices.com www.anmarenterprices.com;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/anmar-engine/anmar.sock;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/anmar.enterprises/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/anmar.enterprises/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.anmar.enterprises) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = anmar.enterprises) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name anmar.enterprises www.anmar.enterprises anmarenterprices.com www.anmarenterprices.com;
    return 404; # managed by Certbot




}